## Exploring Curriculum Access Logs

by Mariam Naqvi and Anna Vu

## Executive Summary

The goal of this project is to answer questions regarding students accessing Codeup's curriculum based on the curriculum logs. The data was acquired from the curriculum logs database, cleaned and manipulated to answer questions. The questions were answered using a combination of pandas manipulation as well as anomaly detection techniques.

### Project Overview

- The tasks for our project were planned using this [Trello board](https://trello.com/b/qAGMpGzT/anomaly-detection-project)
- Python scripts were used to automate the process of acquiring and preparing the data
- The data was cleaned by converting dates to datetime objects, dropping duplicates, removing nulls, encoding new features and renaming columns to be more descriptive

### Key Takeaways

- The prepared dataframe has over 840,000 rows and 12 columns.
- There are 4 different programs available in the dataset:
    - Full-Stack PHP Program
    - Full-Stack Java Program
    - Data Science
    - Front-End Program 
- The most accessed lessons for each program are as follows:
    - Data Science: classification overview 
    - Full Stack PHP and Java:  javascript-i
    - Front End: html-css
- 84% students are in the Full Stack Java program and only 5 students are in the Front End Program.
- 33 students in the Full Stack Java cohorts hardly accessed the curriculum while they were in the program.
    - The highest numbers of these students were found to be in the most recent cohorts of Neptune and Oberon. These students' curriculum access counts could be low since they only recently joined the program.
- There seems to be some suspicious activity going on with one user in the Zion cohort accessing 272 pages in the curriculum in a duration of under 2 hours.
    - This user also used a few different IP addresses. 
    - They also accessed 104 pages in the curriculum a few months post graduation.
- There were 468 pages in the curriculum which were only accessed once.
    - Some of these pages were found to be lessons while the others were professional development pages.
- The following lessons were accessed post graduation:
    - Web development: JavaScript-I, Spring, HTML-CSS
    - Data Science: SQL, Classification Overview, Classification Scaling
    - Full Stack PHP: Jacascript-I, HTML-CSS, Spring
    - Front End: content html-css, favicon, and introduction (expected for staff)

### Data Dictionary

- You can find the data dictionary detailing all the variables used and created [here](https://github.com/naqvi-and-vu/anomaly-detection-project/blob/main/README.md)

Through our analysis we aimed to answer the following questions. This notebook provides answers to each question and an explanation of how that conclusion was reached.

In [1]:
# import libraries and custom modules to use 
import warnings
warnings.filterwarnings("ignore")
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

import numpy as np
import pandas as pd
import math


import seaborn as sns
import acquire as a
import prepare as p
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import MinMaxScaler

In [2]:
# acquire df
df = a.get_curriculum_data()

In [3]:
# quick look at data
df.head()

start_date    end_date           created_at   cohort  program_id  \
0  2015-09-22  2016-02-06  2016-06-14 19:52:26  Hampton         1.0   
1  2015-09-22  2016-02-06  2016-06-14 19:52:26  Hampton         1.0   
2  2015-09-22  2016-02-06  2016-06-14 19:52:26  Hampton         1.0   
3  2015-09-22  2016-02-06  2016-06-14 19:52:26  Hampton         1.0   
4  2018-01-08  2018-05-17  2018-01-08 13:59:10    Teddy         2.0   

         date      time                             endpoint  user_id  \
0  2018-01-26  09:55:03                                    /        1   
1  2018-01-26  09:56:02                              java-ii        1   
2  2018-01-26  09:56:05  java-ii/object-oriented-programming        1   
3  2018-01-26  09:56:06   slides/object_oriented_programming        1   
4  2018-01-26  09:56:24            javascript-i/conditionals        2   

             ip  
0  97.105.19.61  
1  97.105.19.61  
2  97.105.19.61  
3  97.105.19.61  
4  97.105.19.61

In [4]:
#look at the information for our dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 900223 entries, 0 to 900222
Data columns (total 10 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   start_date  847330 non-null  object 
 1   end_date    847330 non-null  object 
 2   created_at  847330 non-null  object 
 3   cohort      847330 non-null  object 
 4   program_id  847330 non-null  float64
 5   date        900223 non-null  object 
 6   time        900223 non-null  object 
 7   endpoint    900222 non-null  object 
 8   user_id     900223 non-null  int64  
 9   ip          900223 non-null  object 
dtypes: float64(1), int64(1), object(8)
memory usage: 68.7+ MB


- We will remove the null values by dropping rows that contain nulls.

In [5]:
# call prepare function
df = p.prep_logs(df)

There are 3518 duplicate rows in your dataset - these will be dropped.
----------------


In [6]:
# look at prepared df
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 843811 entries, 2018-01-26 to 2021-04-21
Data columns (total 12 columns):
 #   Column          Non-Null Count   Dtype         
---  ------          --------------   -----         
 0   start_date      843811 non-null  datetime64[ns]
 1   end_date        843811 non-null  datetime64[ns]
 2   created_at      843811 non-null  object        
 3   cohort          843811 non-null  object        
 4   program_id      843811 non-null  float64       
 5   date            843811 non-null  datetime64[ns]
 6   time            843811 non-null  object        
 7   endpoint        843811 non-null  object        
 8   user_id         843811 non-null  int64         
 9   ip              843811 non-null  object        
 10  accessed_after  843811 non-null  int64         
 11  program_name    843811 non-null  object        
dtypes: datetime64[ns](3), float64(1), int64(2), object(6)
memory usage: 83.7+ MB


In [7]:
# look at prepared df
df.head()

start_date   end_date           created_at   cohort  program_id  \
date                                                                         
2018-01-26 2015-09-22 2016-02-06  2016-06-14 19:52:26  Hampton         1.0   
2018-01-26 2015-09-22 2016-02-06  2016-06-14 19:52:26  Hampton         1.0   
2018-01-26 2015-09-22 2016-02-06  2016-06-14 19:52:26  Hampton         1.0   
2018-01-26 2015-09-22 2016-02-06  2016-06-14 19:52:26  Hampton         1.0   
2018-01-26 2018-01-08 2018-05-17  2018-01-08 13:59:10    Teddy         2.0   

                 date      time                             endpoint  user_id  \
date                                                                            
2018-01-26 2018-01-26  09:55:03                                    /        1   
2018-01-26 2018-01-26  09:56:02                              java-ii        1   
2018-01-26 2018-01-26  09:56:05  java-ii/object-oriented-programming        1   
2018-01-26 2018-01-26  09:56:06   slides/object_oriented_programming        1   
2018-01-26 2018-01-26  09:56:24            javascript-i/conditionals        2   

                      ip  accessed_after     program_name  
date                                                       
2018-01-26  97.105.19.61               1   Full Stack PHP  
2018-01-26  97.105.19.61               1   Full Stack PHP  
2018-01-26  97.105.19.61               1   Full Stack PHP  
2018-01-26  97.105.19.61               1   Full Stack PHP  
2018-01-26  97.105.19.61               0  Web Development

- 2 new features added
- The Full Stack Java program is also referred to as Web Development

### 1. Which lesson appears to attract the most traffic consistently across cohorts (per program)?

There are 4 different programs available in the dataset:
1. Full-Stack PHP Program
2. Full-Stack Java Program
3. Data Science
4. Front-End Program

We checked the value counts for each program's endpoints to see which lesson was referred to the most across cohorts. The following results were found:

- The most commonly accessed page was the home page for all cohorts
- For the PHP and Java programs, the javascript-i lesson was accessed the most.
- For Data Science, the classification overview lesson was accessed the most.
- For the Front-End Program, the html-css lesson was accessed the most.

In [8]:
# check different programs offered and proportion of students in each
df.program_id.value_counts(dropna=False,normalize=True)

2.0    0.842043
3.0    0.121872
1.0    0.036079
4.0    0.000006
Name: program_id, dtype: float64

In [9]:
# find the lesson that is          most accessed for each program
df_program_list = list(df.program_name.value_counts().index)

#return the top, most visited endpoint for each program
for program in df_program_list: 
        #remove endpoints that are the home page, table of contents, and other miscellaneous
        program_df = pd.DataFrame(df[(df.endpoint != '/')&(df.endpoint != 'toc')&(df.endpoint != 'search/search_index.json')&(df.endpoint != 'index.html')].groupby('program_name')['endpoint'].value_counts())
        access_df = program_df.loc[[program]]
        access_df = access_df.endpoint.nlargest(1)
        print(access_df)
        print('\n')
        print('----------------------------------------------')
        print('\n')

program_name     endpoint    
Web Development  javascript-i    17403
Name: endpoint, dtype: int64


----------------------------------------------


program_name  endpoint               
Data Science  classification/overview    1783
Name: endpoint, dtype: int64


----------------------------------------------


program_name    endpoint    
Full Stack PHP  javascript-i    735
Name: endpoint, dtype: int64


----------------------------------------------


program_name  endpoint        
Front End     content/html-css    2
Name: endpoint, dtype: int64


----------------------------------------------




### 2. Are there students who, when active, hardly access the curriculum? If so, what information do you have about these students?

Yes, there are some students who accessed the curriculum less than 50 times in the period that they were active (until 4/21/2021). We decided upon this threshold because that would mean they accessed the curriculum less than twice a week during their active training. 

We found that the 33 of the students belonged to the Web Development (Full Stack Java) cohorts and only 3 students were from Data Science cohorts. 
3 of the cohorts had not graduated by the time the dataset had stopped collecting entries. These students likely did not spend enough time in the program and that may be the reason their access counts are low. 

Some students only accessed the curriculum the first 3 days after their cohort started. They may have dropped out of the program after the 72 hour grace period.

None of the students who hardly accessed the curriculum were from Front End and Full stack php programs.

The hardly_working dataframe included below provides more information about students who hardly accessed the curriculum while in their respective programs.

In [10]:
# find students who accessed curriculum while still active students

df_current = df.loc[df.accessed_after == 0]

In [11]:
# df with students who accessed curriculum while still in the program
df_current = df_current.loc[(df_current.index >= df_current.start_date) & (df_current.index <= df_current.end_date)]


In [12]:
# check the df 
df_current

start_date   end_date           created_at   cohort  program_id  \
date                                                                         
2018-01-26 2018-01-08 2018-05-17  2018-01-08 13:59:10    Teddy         2.0   
2018-01-26 2018-01-08 2018-05-17  2018-01-08 13:59:10    Teddy         2.0   
2018-01-26 2018-01-08 2018-05-17  2018-01-08 13:59:10    Teddy         2.0   
2018-01-26 2018-01-08 2018-05-17  2018-01-08 13:59:10    Teddy         2.0   
2018-01-26 2018-01-08 2018-05-17  2018-01-08 13:59:10    Teddy         2.0   
...               ...        ...                  ...      ...         ...   
2021-04-21 2021-01-25 2021-07-19  2021-01-20 21:31:11    Marco         2.0   
2021-04-21 2021-03-15 2021-09-03  2021-03-15 19:57:09  Neptune         2.0   
2021-04-21 2020-12-07 2021-06-08  2020-12-07 16:58:43     Luna         2.0   
2021-04-21 2020-12-07 2021-06-08  2020-12-07 16:58:43     Luna         2.0   
2021-04-21 2021-01-25 2021-07-19  2021-01-20 21:31:11    Marco         2.0   

                 date      time                               endpoint  \
date                                                                     
2018-01-26 2018-01-26  09:56:24              javascript-i/conditionals   
2018-01-26 2018-01-26  09:56:41                     javascript-i/loops   
2018-01-26 2018-01-26  09:56:46              javascript-i/conditionals   
2018-01-26 2018-01-26  09:56:48                 javascript-i/functions   
2018-01-26 2018-01-26  09:56:59                     javascript-i/loops   
...               ...       ...                                    ...   
2021-04-21 2021-04-21  16:36:09                   jquery/personal-site   
2021-04-21 2021-04-21  16:36:34  html-css/css-ii/bootstrap-grid-system   
2021-04-21 2021-04-21  16:37:48                               java-iii   
2021-04-21 2021-04-21  16:38:14                      java-iii/servlets   
2021-04-21 2021-04-21  16:41:51           javascript-i/bom-and-dom/dom   

            user_id              ip  accessed_after     program_name  
date                                                                  
2018-01-26        2    97.105.19.61               0  Web Development  
2018-01-26        2    97.105.19.61               0  Web Development  
2018-01-26        3    97.105.19.61               0  Web Development  
2018-01-26        3    97.105.19.61               0  Web Development  
2018-01-26        2    97.105.19.61               0  Web Development  
...             ...             ...             ...              ...  
2021-04-21      869    136.50.98.51               0  Web Development  
2021-04-21      948  104.48.214.211               0  Web Development  
2021-04-21      834     67.11.50.23               0  Web Development  
2021-04-21      834     67.11.50.23               0  Web Development  
2021-04-21      875  24.242.150.231               0  Web Development  

[644754 rows x 12 columns]

In [13]:
# create a df with value counts for each user id
user_df = pd.DataFrame(df_current.user_id.value_counts(dropna=False)).reset_index().\
                rename(index=str, columns={'index': 'user_id', 'user_id': 'user_count'})
# create df for each user id and its probability
user_df2 = pd.DataFrame(df_current.user_id.value_counts(dropna=False)/df_current.user_id.count()).reset_index().\
                rename(index=str, columns={'index': 'user_id', 'user_id': 'user_proba'})
# merge the 2 user dfs
user_df = user_df.merge(user_df2)


In [14]:
# merge user_df with the current students df, set date as index and fill null values
df_current = df_current.merge(user_df, on=['user_id'], how='left').fillna(value=0).set_index('date')
df_current.user_proba.value_counts()

0.007409    4777
0.002295    4440
0.002987    3852
0.002758    3556
0.001833    3546
            ... 
0.000009       6
0.000008       5
0.000002       4
0.000006       4
0.000005       3
Name: user_proba, Length: 608, dtype: int64

In [15]:
# students who access curriculum less than 50 times are considered hardly accessing it
hardly_working = df_current[df_current.user_count < 50]

In [16]:
# pull specific columns in this df
hardly_working = hardly_working[['user_id','cohort','program_name','start_date','end_date', 'user_count']]

hardly_working

user_id   cohort     program_name start_date   end_date  \
date                                                                  
2018-01-26       24  Sequoia  Web Development 2017-09-27 2018-02-15   
2018-01-26       24  Sequoia  Web Development 2017-09-27 2018-02-15   
2018-01-26       41  Sequoia  Web Development 2017-09-27 2018-02-15   
2018-01-26       49  Sequoia  Web Development 2017-09-27 2018-02-15   
2018-01-26       49  Sequoia  Web Development 2017-09-27 2018-02-15   
...             ...      ...              ...        ...        ...   
2021-04-21      976   Oberon  Web Development 2021-04-12 2021-10-01   
2021-04-21      973   Oberon  Web Development 2021-04-12 2021-10-01   
2021-04-21      972   Oberon  Web Development 2021-04-12 2021-10-01   
2021-04-21      981  Neptune  Web Development 2021-03-15 2021-09-03   
2021-04-21      981  Neptune  Web Development 2021-03-15 2021-09-03   

            user_count  
date                    
2018-01-26          26  
2018-01-26          26  
2018-01-26          28  
2018-01-26          25  
2018-01-26          25  
...                ...  
2021-04-21          29  
2021-04-21          35  
2021-04-21          34  
2021-04-21          41  
2021-04-21          41  

[755 rows x 6 columns]

In [17]:
# reset index so date is not the index
hardly_working = hardly_working.reset_index()
hardly_working

date  user_id   cohort     program_name start_date   end_date  \
0   2018-01-26       24  Sequoia  Web Development 2017-09-27 2018-02-15   
1   2018-01-26       24  Sequoia  Web Development 2017-09-27 2018-02-15   
2   2018-01-26       41  Sequoia  Web Development 2017-09-27 2018-02-15   
3   2018-01-26       49  Sequoia  Web Development 2017-09-27 2018-02-15   
4   2018-01-26       49  Sequoia  Web Development 2017-09-27 2018-02-15   
..         ...      ...      ...              ...        ...        ...   
750 2021-04-21      976   Oberon  Web Development 2021-04-12 2021-10-01   
751 2021-04-21      973   Oberon  Web Development 2021-04-12 2021-10-01   
752 2021-04-21      972   Oberon  Web Development 2021-04-12 2021-10-01   
753 2021-04-21      981  Neptune  Web Development 2021-03-15 2021-09-03   
754 2021-04-21      981  Neptune  Web Development 2021-03-15 2021-09-03   

     user_count  
0            26  
1            26  
2            28  
3            25  
4            25  
..          ...  
750          29  
751          35  
752          34  
753          41  
754          41  

[755 rows x 7 columns]

In [18]:
# drop any duplicate user ids in the df and keep the most recent access
hardly_working = hardly_working.drop_duplicates(subset='user_id', keep="last")
hardly_working

date  user_id     cohort     program_name start_date   end_date  \
69  2018-02-05       49    Sequoia  Web Development 2017-09-27 2018-02-15   
71  2018-02-07       24    Sequoia  Web Development 2017-09-27 2018-02-15   
78  2018-02-08       41    Sequoia  Web Development 2017-09-27 2018-02-15   
82  2018-09-27      278  Voyageurs  Web Development 2018-05-29 2018-10-11   
100 2019-01-22      340       Zion  Web Development 2019-01-22 2019-06-04   
138 2019-03-19      388  Andromeda  Web Development 2019-03-18 2019-07-30   
150 2019-03-29      371   Yosemite  Web Development 2018-11-05 2019-04-03   
167 2019-08-30      487      Bayes     Data Science 2019-08-19 2020-01-30   
173 2019-11-04      539     Europa  Web Development 2019-11-04 2020-04-17   
208 2019-11-08      529     Europa  Web Development 2019-11-04 2020-04-17   
220 2020-01-14      572    Fortuna  Web Development 2020-01-13 2020-06-23   
245 2020-01-21       64     Europa  Web Development 2019-11-04 2020-04-17   
246 2020-03-23      619   Ganymede  Web Development 2020-03-23 2020-08-20   
264 2020-07-13      697     Darden     Data Science 2020-07-13 2021-01-12   
270 2020-07-14      679     Darden     Data Science 2020-07-13 2021-01-12   
296 2020-09-23      772    Jupiter  Web Development 2020-09-21 2021-03-30   
303 2020-11-08      812   Hyperion  Web Development 2020-05-26 2020-11-10   
306 2020-12-07      832    Jupiter  Web Development 2020-09-21 2021-03-30   
307 2021-01-26      879      Marco  Web Development 2021-01-25 2021-07-19   
323 2021-02-02      889      Marco  Web Development 2021-01-25 2021-07-19   
324 2021-03-15      918    Neptune  Web Development 2021-03-15 2021-09-03   
325 2021-03-15      940    Neptune  Web Development 2021-03-15 2021-09-03   
337 2021-03-15      941    Neptune  Web Development 2021-03-15 2021-09-03   
497 2021-04-15      956     Oberon  Web Development 2021-04-12 2021-10-01   
676 2021-04-20      963     Oberon  Web Development 2021-04-12 2021-10-01   
692 2021-04-20      971     Oberon  Web Development 2021-04-12 2021-10-01   
697 2021-04-20      961     Oberon  Web Development 2021-04-12 2021-10-01   
710 2021-04-20      968     Oberon  Web Development 2021-04-12 2021-10-01   
715 2021-04-20      959     Oberon  Web Development 2021-04-12 2021-10-01   
731 2021-04-21      964     Oberon  Web Development 2021-04-12 2021-10-01   
737 2021-04-21      967     Oberon  Web Development 2021-04-12 2021-10-01   
745 2021-04-21      960     Oberon  Web Development 2021-04-12 2021-10-01   
750 2021-04-21      976     Oberon  Web Development 2021-04-12 2021-10-01   
751 2021-04-21      973     Oberon  Web Development 2021-04-12 2021-10-01   
752 2021-04-21      972     Oberon  Web Development 2021-04-12 2021-10-01   
754 2021-04-21      981    Neptune  Web Development 2021-03-15 2021-09-03   

     user_count  
69           25  
71           26  
78           28  
82            4  
100          18  
138           8  
150          42  
167          17  
173           5  
208          36  
220          12  
245          25  
246           1  
264          13  
270          11  
296          26  
303           7  
306           3  
307           1  
323          16  
324           1  
325           1  
337          12  
497           6  
676          18  
692          44  
697          20  
710          17  
715          41  
731          44  
737          40  
745          48  
750          29  
751          35  
752          34  
754          41

In [19]:
# check what different programs users belong to
hardly_working.program_name.value_counts()


Web Development    33
Data Science        3
Name: program_name, dtype: int64

In [20]:
# find different cohorts that users belong to who don't access the curriculum often
hardly_working.cohort.value_counts()


Oberon       12
Neptune       4
Sequoia       3
Europa        3
Darden        2
Marco         2
Jupiter       2
Voyageurs     1
Ganymede      1
Hyperion      1
Andromeda     1
Zion          1
Fortuna       1
Bayes         1
Yosemite      1
Name: cohort, dtype: int64

In [21]:
# check start date of cohorts
hardly_working.start_date.value_counts()


2021-04-12    12
2021-03-15     4
2019-11-04     3
2017-09-27     3
2021-01-25     2
2020-07-13     2
2020-09-21     2
2019-01-22     1
2020-01-13     1
2020-03-23     1
2018-11-05     1
2019-08-19     1
2020-05-26     1
2018-05-29     1
2019-03-18     1
Name: start_date, dtype: int64

### 3. Is there any suspicious activity, such as users/machines/etc accessing the curriculum who shouldn’t be? Does it appear that any web-scraping is happening? Are there any suspicious IP addresses?

- It appears that there might be some web scraping happening.
- The most frequently used ip address would be the ip address for the school assuming students are accessing the curriculum from codeup's campus.
- We explored the anomalies in number of page views beyond the upper bollinger band.
- User 341 had some suspicious activity with 272 pages viewed on 2019-03-03 and 104 pages viewed on 2020-04-21. 
- The user used a few different ip addresses on 03-03-2019 and the curriculum was accessed after 10pm to midnight.
- The user also accessed a wide range of topics. 
- On 2020-04-21, the user accessed a wide range of topics and viewed 104 pages using a different ip address. This was a while after the student had graduated from the Zion cohort in June 2019.


In [22]:
# most frequently used ip 
df.ip.value_counts().idxmax()

'97.105.19.58'

In [23]:
def prep(df, user):
    '''
    This function takes in a df and a single user. 
    It converts the date column to a datetime object and sets that as the index.
    It also resamples daily counts for number of page views.
    '''
    df = df[df.user_id == user]
    pages = df['endpoint'].resample('d').count()
    return pages

def compute_pct_b(pages, span, weight, user):
    '''
    This function takes in the pages, the number of days, the weight to calculate the standard deviation and the user.
    It calculates the mid, upper and lower bollinger bands and concatenates the upper and lower bands.
    It then creates a new dataframe with the number of page view, midband, upper and lower bands.
    It calculate the %b and adds a user id column to the df and then returns the df.
    '''
    midband = pages.ewm(span=span).mean()
    stdev = pages.ewm(span=span).std()
    ub = midband + stdev * weight
    lb = midband - stdev * weight
    bb = pd.concat([ub, lb], axis=1)
    my_df = pd.concat([pages, midband, bb], axis=1)
    my_df.columns = ['pages', 'midband', 'ub', 'lb']
    my_df['pct_b'] = (my_df['pages'] - my_df['lb'])/(my_df['ub'] - my_df['lb'])
    my_df['user_id'] = user
    return my_df

def find_anomalies(df, user, span, weight):
    '''
    This function takes in a df, user id, number of days as span and the weight to compute %b. 
    It then prepares the df by calling the prep function.
    It also creates a new dataframe by calling the compute pct b function.
    It returns a subset of the df where %b is greater than 1.
    '''
    pages = prep(df, user)
    my_df = compute_pct_b(pages, span, weight, user)
    return my_df[my_df.pct_b > 1]

In [24]:
# test on a single user

user = 68
span = 30
weight = 3

# initialize empty df
anomalies = pd.DataFrame()

# call function to create a new df with anomalies for the user 
user_df = find_anomalies(df, user, span, weight)

# concatenate the above df created with the empty anomalies df
anomalies = pd.concat([anomalies, user_df], axis=0)

In [25]:
# find anomalous activity for user id 68
anomalies

pages   midband         ub         lb     pct_b  user_id
date                                                                
2018-05-04     67  7.035731  60.259707 -46.188246  1.063320       68
2018-06-25     50  4.814414  45.293820 -35.664992  1.058131       68
2018-08-20     17  1.240614  15.592025 -13.110798  1.049054       68
2018-10-16     13  0.898680  10.970734  -9.173375  1.100737       68
2018-11-15     27  1.863468  22.364497 -18.637561  1.113055       68
2019-01-30     21  1.407805  17.354013 -14.538403  1.114321       68
2019-03-25     24  1.622558  19.932129 -16.687012  1.111086       68
2019-06-27      9  0.587115   7.439000  -6.264770  1.113910       68
2019-07-10     14  1.554444  13.962988 -10.854099  1.001491       68
2019-08-07     18  1.966101  17.408340 -13.476138  1.019157       68
2019-08-08     53  5.258610  46.326380 -35.809159  1.081251       68
2019-10-31     46  3.310170  38.242900 -31.622561  1.111029       68

In [26]:
# loop through all users to find anomalies for each
span = 30
weight = 3.5

anomalies = pd.DataFrame()
for u in list(df.user_id.unique()):
    user_df = find_anomalies(df, u, span, weight)
    anomalies = pd.concat([anomalies, user_df], axis=0)

In [27]:
# find anomalous activity for all users
anomalies

pages   midband         ub         lb     pct_b  user_id
date                                                                
2019-01-29     44  3.623334  42.081344 -34.834677  1.024945        1
2019-07-08    101  8.237813  96.472922 -79.997296  1.025653        1
2018-10-15      9  0.581421   8.457413  -7.294571  1.034446        3
2019-01-09      4  0.262470   3.802115  -3.277175  1.027953        3
2019-04-06      2  0.129825   1.889712  -1.630061  1.031334        3
...           ...       ...        ...        ...       ...      ...
2021-01-24      7  0.574393   6.857226  -5.708440  1.011362      817
2021-03-25     59  6.797425  58.410273 -44.815423  1.005713      843
2021-02-23     67  8.229409  66.322904 -49.864086  1.005828      851
2021-04-06     19  1.348943  18.056879 -15.358994  1.028224      854
2021-03-25     15  1.021925  14.239722 -12.195871  1.028760      859

[963 rows x 6 columns]

- A pct_b value above 1 indicates pages accessed are beyond upper bollinger band. 
- In this sitatuation, we care about students who are accessing the curriculum more often than 3 standard deviations.

In [28]:
# look at value counts for pages in anomalies without sorting the counts
anomalies.pages.value_counts(sort = False)

1      43
2      34
3      65
4      74
5      54
       ..
165     1
179     1
192     1
197     1
272     1
Name: pages, Length: 93, dtype: int64

The highest number of page views is 272 so let's investigate that.

In [29]:
# look at a subset of anomalies df where the number of page views is equal to 272
anomalies[anomalies.pages == 272]

pages    midband          ub          lb     pct_b  user_id
date                                                                   
2019-03-03    272  24.721632  266.780128 -217.336864  1.010782      341

- Looks like it is user 341 who has a very high number of page views. We can investigate this user's activity further to check if there is anything suspicous about their IP address.

In [30]:
# pull a subset of data where user id is 341
anomalies[anomalies.user_id == 341]

pages    midband          ub          lb     pct_b  user_id
date                                                                   
2019-03-03    272  24.721632  266.780128 -217.336864  1.010782      341
2020-02-18      3   0.193548    2.817185   -2.430088  1.034840      341
2020-04-21    104   6.928145   97.719968  -83.863678  1.034585      341
2021-02-09     10   0.659630    9.508602   -8.189342  1.027766      341

- Looks like on 2019-03-03 and 2020-04-21 this user had very high number of page views. 

In [31]:
# check different ip addresses for this user
df.ip[df.user_id == 341].value_counts()

97.105.19.58       677
172.124.70.146     457
173.174.243.231    232
204.44.112.76      180
70.123.203.131      25
192.171.117.210      3
Name: ip, dtype: int64

- This user seems to be using a few different IP addresses to access the curriculum. 
- The ip's with suspicious activity are:
    - 173.174.243.231    
    - 204.44.112.76     
- We will look at a subset of the df to further investigate this user's details for the dates of 03-03-2019 and 04-21-2020.

In [32]:
sus_1 = df.loc['2019-03-02':'2019-03-04']

sus_2 = df.loc['2020-04-20':'2020-04-21']

In [33]:
# set to display all rows and columns
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [34]:
# check details for user 341 on 3/3
sus_1[sus_1.user_id == 341]

start_date   end_date           created_at cohort  program_id  \
date                                                                       
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2019-03-03 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zio

In [35]:
# check details for user 341 on 4/21
sus_2[sus_2.user_id == 341]

start_date   end_date           created_at cohort  program_id  \
date                                                                       
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zion         2.0   
2020-04-21 2019-01-22 2019-06-04  2019-01-20 23:18:57   Zio

### 4. Which lessons are least accessed?

There were 458 pages in the curriculum which were only accessed once. In this situation, we are assuming that the least accessed pages would be accessed at least once. Some of the least accessed pages were found to be lessons while the others were professional development pages. There was also one lesson page that seemed erroneous. The following were some of the least accessed lessons:

In [36]:
df.endpoint.value_counts(sort=True).tail(10)

prework/cli/03-filepaths                                         1
html-css/css-i/positioning/specimen/MaterialIcons-Regular.ttf    1
glossary                                                         1
uploads/598dc43df39e2.jpg                                        1
prework/cli/07-editing-files-with-vim                            1
warmups                                                          1
objects/math                                                     1
appendix/3d-plotting                                             1
html-css/css-i/flexbox-fundamentals                              1
user/913                                                         1
Name: endpoint, dtype: int64

In [37]:
# number of pages that were accessed once
df.endpoint.value_counts(sort=True).nsmallest(1, keep='all').count()

468

In [38]:
# all the pages that were accessed once
df.endpoint.value_counts(sort=True).nsmallest(1, keep='all')

capstone/teams                                                                                                                                                                                                                                                             1
grades                                                                                                                                                                                                                                                                     1
ada-capsontes.html                                                                                                                                                                                                                                                         1
11.01.03_Summarize.md                                                                                                                                                                            

### 5. What topics are grads continuing to reference after graduation and into their jobs (for each program)?

- We created the accessed_after variable that is 0 if a student did not access the lesson after graduation and 1 if they did. We found the top 3 lessons graduates of each program access were as follows.

- Full Stack Java (Web Development) 
    - javascript-i  
    - spring          
    - html-css 
- Data Science  
    - Mysql-overview                          
    - classification/overview                   
    - classification/scale_features_or_not
- Full Stack PHP (same lessons as Full Stack Java)  
    - javascript-i    
    - html-css        
    - spring                                     
- Front End     
    - content/html-css                              
    - content/html-css/gitbook/images/favicon.ico   
    - content/html-css/introduction.html


In [ ]:
# create a new df which only shows students who accessed curriculum after graduation
df_grads = df.loc[df.accessed_after==1]

df_grads

In [ ]:
# how many students access the curriculum after graduation
len(df_grads)

In [ ]:
# turn program names into a list
df_program_list = list(df.program_name.value_counts().index)

df_program_list

In [ ]:
# for loop removes non lesson pages and prints top lessons grads access
for program in df_program_list:     
        program_df = pd.DataFrame(df_grads[(df_grads.endpoint != '/')&(df_grads.endpoint != 'toc')&(df_grads.endpoint != 'search/search_index.json')&(df_grads.endpoint != 'index.html')].groupby('program_name')['endpoint'].value_counts())
        # create a separate df for each program
        access_df = program_df.loc[[program]]
        # find top 3 lessons for each program
        access_df = access_df.endpoint.nlargest(3)
        print(access_df)
        print('----------------------------------------------')
        print('\n')

### Conclusion

- Top lessons for Data Science included SQL and Classification while those for Full Stack Java included Javascript I, html CSS and Spring.
- Full Stack PHP and Full Stack Java programs graduates accessed the same top 3 lessons after graduation.
- There is risk of webscraping/crawling and malicious activity as evidenced by one of the students' activity.
- Students with low access rates usually stopped utilizing the program within 3 days of their cohort start date.
- 468 pages in the curriculum were only accessed once.